# Generated by Django 5.0.14 on 2025-06-11 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_document_type'),
        ('optionlists', '0004_reorganize_referral_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='access_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal Only'), ('restricted', 'Restricted Access'), ('confidential', 'Confidential')], default='internal', max_length=20, verbose_name='Access Level'),
        ),
        migrations.AddField(
            model_name='document',
            name='client_id',
            field=models.UUIDField(blank=True, help_text='UUID of the client this document belongs to', null=True, verbose_name='Client ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the document content', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, help_text='File size in bytes', null=True, verbose_name='File Size'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder_category',
            field=models.CharField(choices=[('consent-forms', 'Consent Forms'), ('assessments', 'Assessments'), ('care-plans', 'Care Plans'), ('id-documents', 'ID Documents'), ('medical-records', 'Medical Records'), ('court-orders', 'Court Orders'), ('school-reports', 'School Reports'), ('referral-letters', 'Referral Letters'), ('general', 'General'), ('other', 'Other')], default='general', help_text='Category for SharePoint folder organization', max_length=50, verbose_name='Folder Category'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_confidential',
            field=models.BooleanField(default=False, help_text='Whether this document contains confidential information', verbose_name='Confidential'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_latest_version',
            field=models.BooleanField(default=True, verbose_name='Is Latest Version'),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MIME Type'),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename before any sanitization', max_length=255, null=True, verbose_name='Original Filename'),
        ),
        migrations.AddField(
            model_name='document',
            name='referral_id',
            field=models.UUIDField(blank=True, help_text='UUID of the referral this document belongs to (if referral-specific)', null=True, verbose_name='Referral ID'),
        ),
        migrations.AddField(
            model_name='document',
            name='sharepoint_url',
            field=models.URLField(blank=True, help_text='Direct URL to the file in SharePoint', max_length=500, null=True, verbose_name='SharePoint URL'),
        ),
        migrations.AddField(
            model_name='document',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='Document that replaces this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='common.document', verbose_name='Superseded By'),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags for document categorization', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='document',
            name='upload_error',
            field=models.TextField(blank=True, help_text='Error message if upload failed', null=True, verbose_name='Upload Error'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the file was successfully uploaded to SharePoint', null=True, verbose_name='Uploaded At'),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.CharField(default='1.0', help_text='Document version for tracking changes', max_length=20, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='document',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Flexible metadata for extensibility', verbose_name='Additional Metadata'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sharepoint_id',
            field=models.CharField(blank=True, help_text='SharePoint unique file ID or URL', max_length=255, null=True, verbose_name='SharePoint ID'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded Successfully'), ('failed', 'Upload Failed'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='pending', max_length=20, verbose_name='Upload Status'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['client_id'], name='common_docu_client__ea8e76_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['referral_id'], name='common_docu_referra_414581_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='common_docu_status_046ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder_category'], name='common_docu_folder__dc31d7_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['type'], name='common_docu_type_id_cb4cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_latest_version'], name='common_docu_is_late_d95bd1_idx'),
        ),
    ]
