# Generated by Django 5.2 on 2025-05-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': [models.Case(models.When(code='NZL', then=0), models.When(code='AUS', then=1), default=2, output_field=models.IntegerField()), 'name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'languages',
                'ordering': [models.Case(models.When(code='mi', then=0), models.When(code='en', then=1), models.When(code='sm', then=2), default=3, output_field=models.IntegerField()), 'name'],
            },
        ),
    ]
