# Generated by Django 5.0.14 on 2025-06-06 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grouprolemapping",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="role",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="role",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_by",
        ),
    ]
