# Generated by Django 5.0.14 on 2025-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0004_remove_grouprolemapping_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='custom_permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Custom permissions and settings specific to this role'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive roles cannot be assigned to users'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_system_role',
            field=models.BooleanField(default=False, help_text='System roles cannot be deleted or have their core properties modified'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, help_text='Django permissions associated with this role', to='auth.permission'),
        ),
    ]
