# Generated by Django 5.0.14 on 2025-06-03 07:36

from django.db import migrations
from django.db.utils import IntegrityError


def create_role_mappings(apps, schema_editor):
    """Create mappings between Azure AD groups and application roles.
    
    This migration creates the initial set of Azure AD group to role mappings.
    Update the AZURE_GROUP_ROLES dictionary with your specific group IDs and role names.
    """
    GroupRoleMapping = apps.get_model('users', 'GroupRoleMapping')
    Role = apps.get_model('users', 'Role')
    
    # Map of Azure AD Group IDs to Role names
    # Replace these with your actual Azure AD group IDs and desired role names
    AZURE_GROUP_ROLES = {
        # Format: 'azure-ad-group-id': 'role_name',
        '4e74cb4d-8664-4303-91d8-cf189f1537cd': 'Admin',
        '6a6cf256-ef54-4063-a06e-fcb8f0bc0b82': 'Manager',
        'edbe21c1-bf1b-4ade-85db-02367f5ac9af': 'Provider',
        '23ce2e67-ae64-41e6-902a-43533534a37b': 'Staff',
    }
    
    for group_id, role_name in AZURE_GROUP_ROLES.items():
        try:
            role = Role.objects.get(name=role_name)
            _, created = GroupRoleMapping.objects.get_or_create(
                azure_ad_group_id=group_id,
                defaults={'role': role}
            )
            if created:
                print(f"Created mapping: {group_id} -> {role_name}")
            else:
                print(f"Mapping already exists: {group_id} -> {role_name}")
                
        except Role.DoesNotExist:
            print(f"Warning: Role '{role_name}' does not exist. Skipping mapping for group {group_id}.")
        except IntegrityError as e:
            print(f"Error creating mapping for group {group_id}: {e}")


def remove_role_mappings(apps, schema_editor):
    """Remove all Azure AD group to role mappings."""
    GroupRoleMapping = apps.get_model('users', 'GroupRoleMapping')
    GroupRoleMapping.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_default_roles"),
    ]

    operations = [
        migrations.RunPython(create_role_mappings, remove_role_mappings),
    ]
