# Generated by Django 5.0.14 on 2025-06-03 08:23

from django.db import migrations


def create_role_mappings(apps, schema_editor):
    """Create or update Azure AD group to role mappings with correct role names."""
    GroupRoleMapping = apps.get_model('users', 'GroupRoleMapping')
    Role = apps.get_model('users', 'Role')
    
    # Map of Azure AD Group IDs to Role names
    AZURE_GROUP_ROLES = {
        '4e74cb4d-8664-4303-91d8-cf189f1537cd': 'Admin',
        '6a6cf256-ef54-4063-a06e-fcb8f0bc0b82': 'Manager',
        'edbe21c1-bf1b-4ade-85db-02367f5ac9af': 'Provider',
        '23ce2e67-ae64-41e6-902a-43533534a37b': 'Staff',
    }
    
    # Clear any existing mappings to avoid duplicates
    GroupRoleMapping.objects.all().delete()
    
    # Create new mappings
    for group_id, role_name in AZURE_GROUP_ROLES.items():
        try:
            role = Role.objects.get(name=role_name)
            GroupRoleMapping.objects.create(
                azure_ad_group_id=group_id,
                role=role
            )
            print(f"Created mapping: {group_id} -> {role_name}")
        except Role.DoesNotExist as e:
            print(f"Error: Role '{role_name}' does not exist. {e}")


def reverse_mappings(apps, schema_editor):
    """Reverse the migration if needed."""
    GroupRoleMapping = apps.get_model('users', 'GroupRoleMapping')
    GroupRoleMapping.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_add_azure_ad_role_mappings"),
    ]

    operations = [
        migrations.RunPython(create_role_mappings, reverse_mappings),
    ]
