# Generated by Django 5.0.14 on 2025-06-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_fix_azure_ad_role_mappings"),
    ]

    operations = []
