# Generated by Django 5.0.14 on 2025-06-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("optionlists", "0001_initial"),
        ("programs", "0001_initial"),
        ("referral_management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="referral_management.referral",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="responsible_staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="program_enrolment_responsible_staff",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"option_list__slug": "enrolment-status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolment_statuses",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by_audit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by_audit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="delivery_modes",
            field=models.ManyToManyField(
                limit_choices_to={"option_list__slug": "programs-delivery_modes"},
                related_name="program_delivery_modes",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="locations",
            field=models.ManyToManyField(
                limit_choices_to={"option_list__slug": "programs-locations"},
                related_name="program_locations",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="service_types",
            field=models.ManyToManyField(
                limit_choices_to={"option_list__slug": "programs-service_types"},
                related_name="program_types",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by_audit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programs.program"
            ),
        ),
        migrations.AddField(
            model_name="programassignedstaff",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by_audit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created By",
            ),
        ),
        migrations.AddField(
            model_name="programassignedstaff",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_deleted_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Deleted By",
            ),
        ),
        migrations.AddField(
            model_name="programassignedstaff",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="programassignedstaff",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="programassignedstaff",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by_audit",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Updated By",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="assigned_staff",
            field=models.ManyToManyField(
                through="programs.ProgramAssignedStaff", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="programfunding",
            name="funding_agency",
            field=models.ForeignKey(
                limit_choices_to={"option_list__slug": "programs-funding_agencies"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funded_programs",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="programfunding",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funding_links",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="funding_agencies",
            field=models.ManyToManyField(
                limit_choices_to={"option_list__slug": "programs-funding_agencies"},
                related_name="program_funding_agencies",
                through="programs.ProgramFunding",
                to="optionlists.optionlistitem",
            ),
        ),
        migrations.AddField(
            model_name="programregion",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="region_links",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="programregion",
            name="region",
            field=models.ForeignKey(
                limit_choices_to={"option_list__slug": "programs-regions"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="program_regions_link",
                to="optionlists.optionlistitem",
            ),
        ),
    ]
