# Generated by Django 5.0.14 on 2025-06-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='referral_schema',
            field=models.JSONField(blank=True, help_text='JSON schema defining program-specific fields for referrals (e.g., school, year level for SWiS)', null=True),
        ),
    ]
