# Generated by Django 5.0.14 on 2025-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "azure_oid",
                    models.CharField(
                        db_index=True,
                        help_text="Azure AD Object ID for the user. This is the primary immutable identifier.",
                        max_length=36,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Azure AD Profile",
                "verbose_name_plural": "User Azure AD Profiles",
            },
        ),
    ]
