# Generated by Django 5.0.14 on 2025-06-02 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "azure_oid",
                    models.CharField(
                        db_index=True,
                        help_text="Azure AD Object ID for the user. This is the primary immutable identifier.",
                        max_length=36,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="The Django User instance.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="azure_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Azure AD Profile",
                "verbose_name_plural": "User Azure AD Profiles",
            },
        ),
    ]
