# Generated by Django 5.0.14 on 2025-06-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Notes"
            ),
        ),
    ]
