# Generated by Django 5.0.14 on 2025-06-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_management', '0002_alter_referral_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referral',
            new_name='referral_ma_type_c9f7ea_idx',
            old_name='referral_ma_type_id_01466d_idx',
        ),
        migrations.AlterField(
            model_name='referral',
            name='type',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='incoming', max_length=20, verbose_name='Referral Type'),
        ),
    ]
