# Generated by Django 5.0.14 on 2025-06-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0005_add_client_relationship'),
        ('referral_management', '0003_change_referral_type_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Leave blank for new clients or self-referrals until client record is created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='client_management.client', verbose_name='Client'),
        ),
    ]
