# Generated by Django 5.0.14 on 2025-06-11 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_add_program_specific_fields'),
        ('referral_management', '0004_add_client_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='external_reference_number',
            field=models.CharField(blank=True, help_text='Reference number from referring organisation', max_length=100, null=True, verbose_name='External Reference Number'),
        ),
        migrations.AddField(
            model_name='referral',
            name='program_data',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data specific to the target program', verbose_name='Program-Specific Data'),
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_source',
            field=models.CharField(choices=[('external_agency', 'External Agency'), ('school', 'School'), ('self_referral', 'Self-Referral'), ('internal', 'Internal Transfer'), ('family', 'Family/Whānau'), ('other', 'Other')], default='external_agency', help_text='How did this referral come to us?', max_length=30, verbose_name='Referral Source'),
        ),
        migrations.AddField(
            model_name='referral',
            name='target_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='programs.program', verbose_name='Target Program'),
        ),
    ]
