# Generated by Django 5.0.14 on 2025-06-11 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionlists', '0003_add_enrolment_statuses'),
        ('programs', '0003_add_program_specific_fields'),
        ('referral_management', '0005_add_program_specific_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approval Date'),
        ),
        migrations.AddField(
            model_name='referral',
            name='approval_reason',
            field=models.TextField(blank=True, help_text='Explanation of why approval is required', null=True, verbose_name='Approval Reason'),
        ),
        migrations.AddField(
            model_name='referral',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_program',
            field=models.ForeignKey(blank=True, help_text='Program actually assigned to handle this referral', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_referrals', to='programs.program', verbose_name='Assigned Program'),
        ),
        migrations.AddField(
            model_name='referral',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for this referral', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff'),
        ),
        migrations.AddField(
            model_name='referral',
            name='commencement_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commencement_approved_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Commencement Approved By'),
        ),
        migrations.AddField(
            model_name='referral',
            name='commencement_date',
            field=models.DateField(blank=True, help_text='Date when service delivery actually began', null=True, verbose_name='Service Commencement Date'),
        ),
        migrations.AddField(
            model_name='referral',
            name='decline_explanation',
            field=models.TextField(blank=True, help_text='Additional explanation for decline (required for "Other" reason)', null=True, verbose_name='Decline Explanation'),
        ),
        migrations.AddField(
            model_name='referral',
            name='decline_reason',
            field=models.ForeignKey(blank=True, help_text='Reason for declining this referral', limit_choices_to={'option_list__slug': 'decline-reasons'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='declined_referrals', to='optionlists.optionlistitem', verbose_name='Decline Reason'),
        ),
        migrations.AddField(
            model_name='referral',
            name='program_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='program_assigned_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Program Assigned By'),
        ),
        migrations.AddField(
            model_name='referral',
            name='program_assigned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Program Assigned Date'),
        ),
        migrations.AddField(
            model_name='referral',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Whether this referral requires supervisory approval', verbose_name='Requires Approval'),
        ),
        migrations.AddField(
            model_name='referral',
            name='staff_assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignment_referrals', to=settings.AUTH_USER_MODEL, verbose_name='Staff Assigned By'),
        ),
        migrations.AddField(
            model_name='referral',
            name='staff_assigned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Staff Assigned Date'),
        ),
    ]
