# Generated by Django 5.0.14 on 2025-06-11 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_document_access_level_document_client_id_and_more'),
        ('optionlists', '0004_reorganize_referral_statuses'),
        ('referral_management', '0006_add_approval_and_assignment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('obtained', 'Obtained'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], default='pending', help_text='Current status of this consent', max_length=20, verbose_name='Consent Status')),
                ('consent_date', models.DateField(blank=True, help_text='Date when consent was obtained', null=True, verbose_name='Consent Date')),
                ('withdrawal_date', models.DateField(blank=True, help_text='Date when consent was withdrawn (if applicable)', null=True, verbose_name='Withdrawal Date')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when consent expires (if applicable)', null=True, verbose_name='Expiry Date')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this consent record', null=True, verbose_name='Notes')),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Reason for consent withdrawal', null=True, verbose_name='Withdrawal Reason')),
                ('consent_type', models.ForeignKey(help_text='Type of consent being tracked', limit_choices_to={'option_list__slug': 'consent-types'}, on_delete=django.db.models.deletion.PROTECT, related_name='consent_type_records', to='optionlists.optionlistitem', verbose_name='Consent Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_audit', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('document', models.ForeignKey(blank=True, help_text='Associated consent document or form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='common.document', verbose_name='Document')),
                ('obtained_by', models.ForeignKey(blank=True, help_text='Staff member who obtained the consent', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obtained_consents', to=settings.AUTH_USER_MODEL, verbose_name='Obtained By')),
                ('referral', models.ForeignKey(help_text='Referral this consent record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='referral_management.referral', verbose_name='Referral')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by_audit', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
                ('withdrawn_by', models.ForeignKey(blank=True, help_text='Staff member who recorded the withdrawal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_consents', to=settings.AUTH_USER_MODEL, verbose_name='Withdrawn By')),
            ],
            options={
                'verbose_name': 'Consent Record',
                'verbose_name_plural': 'Consent Records',
                'ordering': ['referral', 'consent_type', '-consent_date'],
                'indexes': [models.Index(fields=['referral', 'consent_type'], name='referral_ma_referra_7a04ed_idx'), models.Index(fields=['status'], name='referral_ma_status_47daf9_idx'), models.Index(fields=['consent_date'], name='referral_ma_consent_435943_idx'), models.Index(fields=['expiry_date'], name='referral_ma_expiry__bafb48_idx')],
                'unique_together': {('referral', 'consent_type')},
            },
        ),
    ]
