# Generated by Django 5.0.14 on 2025-06-11 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionlists', '0004_reorganize_referral_statuses'),
        ('referral_management', '0007_consentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='service_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'option_list__slug': 'referral-service-types'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referral_service_type_referrals', to='optionlists.optionlistitem', verbose_name='Service Type'),
        ),
    ]
