# Generated by Django 5.0.14 on 2025-06-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="extended_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional data fields for future extensions",
                null=True,
                verbose_name="Extended Data",
            ),
        ),
    ]
