# Generated by Django 5.0.14 on 2025-06-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client_management", "0002_alter_client_extended_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="cultural_identity",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Cultural background information (extensible JSON field)",
                null=True,
                verbose_name="Cultural Identity",
            ),
        ),
    ]
