# Generated by Django 5.0.14 on 2025-06-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0004_update_primary_language_to_reference_data'),
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='primary_language',
            field=models.ForeignKey(blank=True, help_text="Client's preferred language", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_language_clients', to='reference_data.language', verbose_name='Primary Language'),
        ),
    ]
