# Generated by Django 5.0.14 on 2025-06-11 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0006_add_gender_field'),
        ('optionlists', '0004_reorganize_referral_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientEmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('first_name', models.CharField(help_text="Emergency contact's first name", max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text="Emergency contact's last name", max_length=100, verbose_name='Last Name')),
                ('phone', models.CharField(help_text='Primary phone number for emergency contact', max_length=50, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, help_text='Full address of emergency contact', null=True, verbose_name='Address')),
                ('is_primary', models.BooleanField(default=False, help_text='Whether this is the primary emergency contact', verbose_name='Primary Contact')),
                ('priority_order', models.PositiveIntegerField(default=1, help_text='Order of contact priority (1 = first to contact)', verbose_name='Priority Order')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this emergency contact', null=True, verbose_name='Notes')),
                ('availability_notes', models.TextField(blank=True, help_text='When this contact is available or any restrictions', null=True, verbose_name='Availability Notes')),
                ('client', models.ForeignKey(help_text='Client this emergency contact belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='client_management.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by_audit', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_by', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('relationship', models.ForeignKey(help_text='Relationship to the client', limit_choices_to={'option_list__slug': 'emergency-contact-relationships'}, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_contact_relationships', to='optionlists.optionlistitem', verbose_name='Relationship')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by_audit', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['client', 'priority_order', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['client', 'priority_order'], name='client_mana_client__86b857_idx'), models.Index(fields=['client', 'is_primary'], name='client_mana_client__5980ca_idx'), models.Index(fields=['relationship'], name='client_mana_relatio_f169e1_idx')],
                'unique_together': {('client', 'priority_order')},
            },
        ),
    ]
