# Generated by Django 5.0.14 on 2025-06-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0007_clientemergencycontact'),
        ('optionlists', '0004_reorganize_referral_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='iwi_hapu',
            field=models.ForeignKey(blank=True, help_text="Client's iwi or hapū affiliation", limit_choices_to={'option_list__slug': 'iwi-hapu'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='iwi_hapu_clients', to='optionlists.optionlistitem', verbose_name='Iwi/Hapū Affiliation'),
        ),
        migrations.AddField(
            model_name='client',
            name='spiritual_needs',
            field=models.ForeignKey(blank=True, help_text="Client's spiritual or religious practices", limit_choices_to={'option_list__slug': 'spiritual-needs'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spiritual_needs_clients', to='optionlists.optionlistitem', verbose_name='Spiritual Needs'),
        ),
    ]
