# Generated by Django 5.0.14 on 2025-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_management', '0008_client_iwi_hapu_client_spiritual_needs'),
    ]

    operations = [
        # Remove the old unique constraint
        migrations.RunSQL(
            "ALTER TABLE client_management_clientemergencycontact DROP CONSTRAINT IF EXISTS client_management_client_client_id_priority_order_1eef052a_uniq;",
            reverse_sql="-- Cannot easily reverse this operation"
        ),
        
        # Add a new unique constraint that excludes soft-deleted records
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX client_management_clientemergencycontact_active_unique
            ON client_management_clientemergencycontact (client_id, priority_order)
            WHERE is_deleted = FALSE;
            """,
            reverse_sql="DROP INDEX IF EXISTS client_management_clientemergencycontact_active_unique;"
        ),
    ]
