name: Build and deploy Python backend to Azure Web App - mtkcare-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write # Required for Azure login with OIDC
  contents: read  # Required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        working-directory: ./backend
        run: zip ../release.zip . -r -x "venv/*" # Package current dir, output to parent, exclude venv

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip # Zipped file is in the root of the checkout

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app # This downloads release.zip into the current working directory

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'mtkcare-backend'
          slot-name: 'Production'
          package: release.zip # Deploy the zip file directly
